### ISSUE TITLE
KeyError: 'rq'

### ISSUE THREAD

**Issue by zbo14** [neuroeddu/Auto-qPCR#7]
I'm running Auto-qPCR in a Docker container and keep getting the following error when I submit the example data:

```
Started
Model: relative_dCT

Files upload complete.
Gene names if they are included in file names: 
Quencher: 
Task: UNKNOWN
Endogenous control genes: ACTIN
Cut-off: 0.3
Maximum Outliers: 0.5
Preserve highly variable replicates: False
Target Order: 
Sample Order: 
Control Sample: 
Additional column names: 
Number of groups: None
Group column name: 
Group name: 
Column name A: 
Column Name B: 
Group names for column A: 
Group names for column B: 
Repeated measures: False
Normal distribution: True
Error occurred: 'rq'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'rq'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/application/routes.py", line 199, in transform_view
    colnames)
  File "/usr/src/app/application/AUTOqPCR.py", line 55, in process_data
    data, data_summary, data_summary_w_group, targets, samples = relative.process(data, colnames, target_sorter, sample_sorter)
  File "/usr/src/app/application/relative.py", line 52, in process
    mean = target_sample_data['rq'].mean()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'rq'

```

Building the Docker image and running the server inside the container work fine. It only errors when I submit data.

**Comment by zbo14** [comment]
Closing this! I think my input parameters were incorrect/causing the error
